services:
  app:
    container_name: pokedex
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8181"
    restart: always
    image: pokedex
    depends_on:
      postgres:
        condition: service_healthy

  solace:
    container_name: solace
    image: solace/solace-pubsub-standard:latest
    shm_size: 1g
    ports:
      - "8080:8080"
      - "55555:55555"
    restart: always
    environment:
      - username_admin_globalaccesslevel=admin
      - username_admin_password=admin

  postgres:
    container_name: postgres
    image: postgres
    ports:
      - "5432:5432"
    expose:
      - "5432"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pokedex
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
